#pragma config(Motor,  port2,           X1,            tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port3,           X2,            tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port4,           Y1,            tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port5,           Y2,            tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true){
		motor[X1] = vexRT[Ch1];
		motor[X2] = vexRT[Ch1];
		motor[Y1] = vexRT[Ch2];
		motor[Y2] = vexRT[Ch2];
	}
}
