#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, I2C_1,  Y1Encoder,      sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_2,  X2Encoder,      sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_3,  X1Encoder,      sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port2,           X1,            tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port3,           X2,            tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port4,           Y1,            tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port5,           Y2,            tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int X = 630;
	int Y = 630;
	int Speed = 127;
//	int encoder = 0

	SensorValue[X1Encoder] = 0;
	SensorValue[X2Encoder] = 0;
	SensorValue[Y1Encoder] = 0;



	while(SensorValue[X1Encoder] < X || SensorValue[Y1Encoder] < Y){
		/*Virtually bind motors X1 and X2
		if (SensorValue[X1Encoder] == SensorValue[X2Encoder]){
		motor[X1] = Speed;
		motor[X2] = Speed;
		}

		if (SensorValue[X1Encoder] <= SensorValue[X2Encoder]){
		motor[X1] = Speed;
		motor[X2] = Speed/1.5;
		}

		if (SensorValue[X1Encoder] >= SensorValue[X2Encoder]){
		motor[X1] = Speed/1.5;
		motor[X2] = Speed;
		}*/

		//Move to desird Y coordinate
		if (SensorValue[Y1Encoder] > -Y){
		motor[Y1] = Speed;
		motor[Y2] = Speed;
		}

	/*if (SensorValue[Y1Encoder] < Y){
		motor[Y1] = -Speed;
		motor[Y2] = -Speed;
		}*/

		//Move to desired X coordinate
		if (SensorValue[X1Encoder] < X){
		motor[X1] = Speed;
		motor[X2] = Speed;
		}

		//Move to desired X coordinate
		if (SensorValue[X1Encoder] > X){
		motor[X1] = 0;
		motor[X2] = 0;
		}


	}
}
