#pragma config(Sensor, in1,    Gyro,           sensorGyro)
#pragma config(Sensor, I2C_1,  X2Encoder,      sensorNone)
#pragma config(Sensor, I2C_2,  Y1Encoder,      sensorNone)
#pragma config(Sensor, I2C_3,  X1Encoder,      sensorNone)
#pragma config(Motor,  port2,           X1,            tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port3,           X2,            tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port4,           Y1,            tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port5,           Y2,            tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

	float X = 1630;
	float Y = 630;
	int Speed = 127;
	float param = X/Y;
	float angle = atan(param)*180/3.1415;
	float dist = sqrt((X*X)+(Y*Y));

task main()
{
	//Calibrate Gyro// set gyro to 0
	SensorType[in1] = sensorNone;
  wait1Msec(1000);
  SensorType[in1] = sensorGyro;
  wait1Msec(1000);


	while(abs(SensorValue[Gyro]) < angle)
  {
    motor[X1] = 25;
  }
  motor[X1] = 0;

  while(SensorValue[X1Encoder] < dist)
	{

	}
}
